package com.gcms.pojo;

import java.util.Date;

public class Appointment extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.handle_user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long handleUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.app_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Date appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.info
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private String info;
    private String address;
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.status
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Integer status;

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id
     *
     * @return the value of appointment.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id
     *
     * @param id the value for appointment.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.user_id
     *
     * @return the value of appointment.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.user_id
     *
     * @param userId the value for appointment.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.handle_user_id
     *
     * @return the value of appointment.handle_user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getHandleUserId() {
        return handleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.handle_user_id
     *
     * @param handleUserId the value for appointment.handle_user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setHandleUserId(Long handleUserId) {
        this.handleUserId = handleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.app_time
     *
     * @return the value of appointment.app_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.app_time
     *
     * @param appTime the value for appointment.app_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.info
     *
     * @return the value of appointment.info
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.info
     *
     * @param info the value for appointment.info
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.create_time
     *
     * @return the value of appointment.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.create_time
     *
     * @param createTime the value for appointment.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.status
     *
     * @return the value of appointment.status
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.status
     *
     * @param status the value for appointment.status
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}