package com.gcms.pojo;

import java.util.Date;

public class GarbageType extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garbage_type.id
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garbage_type.tip
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    private String tip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garbage_type.Include
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    private String include;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garbage_type.ask
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    private String ask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garbage_type.type
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garbage_type.create_time
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garbage_type.id
     *
     * @return the value of garbage_type.id
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garbage_type.id
     *
     * @param id the value for garbage_type.id
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garbage_type.tip
     *
     * @return the value of garbage_type.tip
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public String getTip() {
        return tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garbage_type.tip
     *
     * @param tip the value for garbage_type.tip
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public void setTip(String tip) {
        this.tip = tip == null ? null : tip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garbage_type.Include
     *
     * @return the value of garbage_type.Include
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public String getInclude() {
        return include;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garbage_type.Include
     *
     * @param include the value for garbage_type.Include
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public void setInclude(String include) {
        this.include = include == null ? null : include.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garbage_type.ask
     *
     * @return the value of garbage_type.ask
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public String getAsk() {
        return ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garbage_type.ask
     *
     * @param ask the value for garbage_type.ask
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public void setAsk(String ask) {
        this.ask = ask == null ? null : ask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garbage_type.type
     *
     * @return the value of garbage_type.type
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garbage_type.type
     *
     * @param type the value for garbage_type.type
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garbage_type.create_time
     *
     * @return the value of garbage_type.create_time
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garbage_type.create_time
     *
     * @param createTime the value for garbage_type.create_time
     *
     * @mbg.generated Fri May 01 16:27:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}