package com.gcms.pojo;

import java.util.Date;

public class Search extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.content
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.view_count
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.id
     *
     * @return the value of search.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.id
     *
     * @param id the value for search.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.content
     *
     * @return the value of search.content
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.content
     *
     * @param content the value for search.content
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.user_id
     *
     * @return the value of search.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.user_id
     *
     * @param userId the value for search.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.view_count
     *
     * @return the value of search.view_count
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.view_count
     *
     * @param viewCount the value for search.view_count
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.create_time
     *
     * @return the value of search.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.create_time
     *
     * @param createTime the value for search.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}