package com.gcms.pojo;

import java.util.Date;

public class UserRank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Long id;
    private Integer moneyRank;

    public Integer getMoneyRank() {
        return moneyRank;
    }

    public void setMoneyRank(Integer moneyRank) {
        this.moneyRank = moneyRank;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.recyclable_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Double recyclableGram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.dry_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Double dryGram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.wet_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Double wetGram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.harmful_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Double harmfulGram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.recyclable_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Double recyclableRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.dry_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Integer dryRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.wet_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Integer wetRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.harmful_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Integer harmfulRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.city_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Integer cityRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rank.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.id
     *
     * @return the value of user_rank.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.id
     *
     * @param id the value for user_rank.id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.user_id
     *
     * @return the value of user_rank.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.user_id
     *
     * @param userId the value for user_rank.user_id
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.recyclable_gram
     *
     * @return the value of user_rank.recyclable_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Double getRecyclableGram() {
        return recyclableGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.recyclable_gram
     *
     * @param recyclableGram the value for user_rank.recyclable_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setRecyclableGram(Double recyclableGram) {
        this.recyclableGram = recyclableGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.dry_gram
     *
     * @return the value of user_rank.dry_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Double getDryGram() {
        return dryGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.dry_gram
     *
     * @param dryGram the value for user_rank.dry_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setDryGram(Double dryGram) {
        this.dryGram = dryGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.wet_gram
     *
     * @return the value of user_rank.wet_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Double getWetGram() {
        return wetGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.wet_gram
     *
     * @param wetGram the value for user_rank.wet_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setWetGram(Double wetGram) {
        this.wetGram = wetGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.harmful_gram
     *
     * @return the value of user_rank.harmful_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Double getHarmfulGram() {
        return harmfulGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.harmful_gram
     *
     * @param harmfulGram the value for user_rank.harmful_gram
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setHarmfulGram(Double harmfulGram) {
        this.harmfulGram = harmfulGram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.recyclable_rank
     *
     * @return the value of user_rank.recyclable_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Double getRecyclableRank() {
        return recyclableRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.recyclable_rank
     *
     * @param recyclableRank the value for user_rank.recyclable_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setRecyclableRank(Double recyclableRank) {
        this.recyclableRank = recyclableRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.dry_rank
     *
     * @return the value of user_rank.dry_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Integer getDryRank() {
        return dryRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.dry_rank
     *
     * @param dryRank the value for user_rank.dry_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setDryRank(Integer dryRank) {
        this.dryRank = dryRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.wet_rank
     *
     * @return the value of user_rank.wet_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Integer getWetRank() {
        return wetRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.wet_rank
     *
     * @param wetRank the value for user_rank.wet_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setWetRank(Integer wetRank) {
        this.wetRank = wetRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.harmful_rank
     *
     * @return the value of user_rank.harmful_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Integer getHarmfulRank() {
        return harmfulRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.harmful_rank
     *
     * @param harmfulRank the value for user_rank.harmful_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setHarmfulRank(Integer harmfulRank) {
        this.harmfulRank = harmfulRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.rank
     *
     * @return the value of user_rank.rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.rank
     *
     * @param rank the value for user_rank.rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.city_rank
     *
     * @return the value of user_rank.city_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Integer getCityRank() {
        return cityRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.city_rank
     *
     * @param cityRank the value for user_rank.city_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setCityRank(Integer cityRank) {
        this.cityRank = cityRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rank.create_time
     *
     * @return the value of user_rank.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rank.create_time
     *
     * @param createTime the value for user_rank.create_time
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}