package com.gcms.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserRankExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public UserRankExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramIsNull() {
            addCriterion("recyclable_gram is null");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramIsNotNull() {
            addCriterion("recyclable_gram is not null");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramEqualTo(Double value) {
            addCriterion("recyclable_gram =", value, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramNotEqualTo(Double value) {
            addCriterion("recyclable_gram <>", value, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramGreaterThan(Double value) {
            addCriterion("recyclable_gram >", value, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramGreaterThanOrEqualTo(Double value) {
            addCriterion("recyclable_gram >=", value, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramLessThan(Double value) {
            addCriterion("recyclable_gram <", value, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramLessThanOrEqualTo(Double value) {
            addCriterion("recyclable_gram <=", value, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramIn(List<Double> values) {
            addCriterion("recyclable_gram in", values, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramNotIn(List<Double> values) {
            addCriterion("recyclable_gram not in", values, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramBetween(Double value1, Double value2) {
            addCriterion("recyclable_gram between", value1, value2, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableGramNotBetween(Double value1, Double value2) {
            addCriterion("recyclable_gram not between", value1, value2, "recyclableGram");
            return (Criteria) this;
        }

        public Criteria andDryGramIsNull() {
            addCriterion("dry_gram is null");
            return (Criteria) this;
        }

        public Criteria andDryGramIsNotNull() {
            addCriterion("dry_gram is not null");
            return (Criteria) this;
        }

        public Criteria andDryGramEqualTo(Double value) {
            addCriterion("dry_gram =", value, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramNotEqualTo(Double value) {
            addCriterion("dry_gram <>", value, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramGreaterThan(Double value) {
            addCriterion("dry_gram >", value, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramGreaterThanOrEqualTo(Double value) {
            addCriterion("dry_gram >=", value, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramLessThan(Double value) {
            addCriterion("dry_gram <", value, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramLessThanOrEqualTo(Double value) {
            addCriterion("dry_gram <=", value, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramIn(List<Double> values) {
            addCriterion("dry_gram in", values, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramNotIn(List<Double> values) {
            addCriterion("dry_gram not in", values, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramBetween(Double value1, Double value2) {
            addCriterion("dry_gram between", value1, value2, "dryGram");
            return (Criteria) this;
        }

        public Criteria andDryGramNotBetween(Double value1, Double value2) {
            addCriterion("dry_gram not between", value1, value2, "dryGram");
            return (Criteria) this;
        }

        public Criteria andWetGramIsNull() {
            addCriterion("wet_gram is null");
            return (Criteria) this;
        }

        public Criteria andWetGramIsNotNull() {
            addCriterion("wet_gram is not null");
            return (Criteria) this;
        }

        public Criteria andWetGramEqualTo(Double value) {
            addCriterion("wet_gram =", value, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramNotEqualTo(Double value) {
            addCriterion("wet_gram <>", value, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramGreaterThan(Double value) {
            addCriterion("wet_gram >", value, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramGreaterThanOrEqualTo(Double value) {
            addCriterion("wet_gram >=", value, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramLessThan(Double value) {
            addCriterion("wet_gram <", value, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramLessThanOrEqualTo(Double value) {
            addCriterion("wet_gram <=", value, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramIn(List<Double> values) {
            addCriterion("wet_gram in", values, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramNotIn(List<Double> values) {
            addCriterion("wet_gram not in", values, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramBetween(Double value1, Double value2) {
            addCriterion("wet_gram between", value1, value2, "wetGram");
            return (Criteria) this;
        }

        public Criteria andWetGramNotBetween(Double value1, Double value2) {
            addCriterion("wet_gram not between", value1, value2, "wetGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramIsNull() {
            addCriterion("harmful_gram is null");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramIsNotNull() {
            addCriterion("harmful_gram is not null");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramEqualTo(Double value) {
            addCriterion("harmful_gram =", value, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramNotEqualTo(Double value) {
            addCriterion("harmful_gram <>", value, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramGreaterThan(Double value) {
            addCriterion("harmful_gram >", value, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramGreaterThanOrEqualTo(Double value) {
            addCriterion("harmful_gram >=", value, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramLessThan(Double value) {
            addCriterion("harmful_gram <", value, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramLessThanOrEqualTo(Double value) {
            addCriterion("harmful_gram <=", value, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramIn(List<Double> values) {
            addCriterion("harmful_gram in", values, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramNotIn(List<Double> values) {
            addCriterion("harmful_gram not in", values, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramBetween(Double value1, Double value2) {
            addCriterion("harmful_gram between", value1, value2, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andHarmfulGramNotBetween(Double value1, Double value2) {
            addCriterion("harmful_gram not between", value1, value2, "harmfulGram");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankIsNull() {
            addCriterion("recyclable_rank is null");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankIsNotNull() {
            addCriterion("recyclable_rank is not null");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankEqualTo(Double value) {
            addCriterion("recyclable_rank =", value, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankNotEqualTo(Double value) {
            addCriterion("recyclable_rank <>", value, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankGreaterThan(Double value) {
            addCriterion("recyclable_rank >", value, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankGreaterThanOrEqualTo(Double value) {
            addCriterion("recyclable_rank >=", value, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankLessThan(Double value) {
            addCriterion("recyclable_rank <", value, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankLessThanOrEqualTo(Double value) {
            addCriterion("recyclable_rank <=", value, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankIn(List<Double> values) {
            addCriterion("recyclable_rank in", values, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankNotIn(List<Double> values) {
            addCriterion("recyclable_rank not in", values, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankBetween(Double value1, Double value2) {
            addCriterion("recyclable_rank between", value1, value2, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andRecyclableRankNotBetween(Double value1, Double value2) {
            addCriterion("recyclable_rank not between", value1, value2, "recyclableRank");
            return (Criteria) this;
        }

        public Criteria andDryRankIsNull() {
            addCriterion("dry_rank is null");
            return (Criteria) this;
        }

        public Criteria andDryRankIsNotNull() {
            addCriterion("dry_rank is not null");
            return (Criteria) this;
        }

        public Criteria andDryRankEqualTo(Integer value) {
            addCriterion("dry_rank =", value, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankNotEqualTo(Integer value) {
            addCriterion("dry_rank <>", value, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankGreaterThan(Integer value) {
            addCriterion("dry_rank >", value, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("dry_rank >=", value, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankLessThan(Integer value) {
            addCriterion("dry_rank <", value, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankLessThanOrEqualTo(Integer value) {
            addCriterion("dry_rank <=", value, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankIn(List<Integer> values) {
            addCriterion("dry_rank in", values, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankNotIn(List<Integer> values) {
            addCriterion("dry_rank not in", values, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankBetween(Integer value1, Integer value2) {
            addCriterion("dry_rank between", value1, value2, "dryRank");
            return (Criteria) this;
        }

        public Criteria andDryRankNotBetween(Integer value1, Integer value2) {
            addCriterion("dry_rank not between", value1, value2, "dryRank");
            return (Criteria) this;
        }

        public Criteria andWetRankIsNull() {
            addCriterion("wet_rank is null");
            return (Criteria) this;
        }

        public Criteria andWetRankIsNotNull() {
            addCriterion("wet_rank is not null");
            return (Criteria) this;
        }

        public Criteria andWetRankEqualTo(Integer value) {
            addCriterion("wet_rank =", value, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankNotEqualTo(Integer value) {
            addCriterion("wet_rank <>", value, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankGreaterThan(Integer value) {
            addCriterion("wet_rank >", value, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("wet_rank >=", value, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankLessThan(Integer value) {
            addCriterion("wet_rank <", value, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankLessThanOrEqualTo(Integer value) {
            addCriterion("wet_rank <=", value, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankIn(List<Integer> values) {
            addCriterion("wet_rank in", values, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankNotIn(List<Integer> values) {
            addCriterion("wet_rank not in", values, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankBetween(Integer value1, Integer value2) {
            addCriterion("wet_rank between", value1, value2, "wetRank");
            return (Criteria) this;
        }

        public Criteria andWetRankNotBetween(Integer value1, Integer value2) {
            addCriterion("wet_rank not between", value1, value2, "wetRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankIsNull() {
            addCriterion("harmful_rank is null");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankIsNotNull() {
            addCriterion("harmful_rank is not null");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankEqualTo(Integer value) {
            addCriterion("harmful_rank =", value, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankNotEqualTo(Integer value) {
            addCriterion("harmful_rank <>", value, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankGreaterThan(Integer value) {
            addCriterion("harmful_rank >", value, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("harmful_rank >=", value, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankLessThan(Integer value) {
            addCriterion("harmful_rank <", value, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankLessThanOrEqualTo(Integer value) {
            addCriterion("harmful_rank <=", value, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankIn(List<Integer> values) {
            addCriterion("harmful_rank in", values, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankNotIn(List<Integer> values) {
            addCriterion("harmful_rank not in", values, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankBetween(Integer value1, Integer value2) {
            addCriterion("harmful_rank between", value1, value2, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andHarmfulRankNotBetween(Integer value1, Integer value2) {
            addCriterion("harmful_rank not between", value1, value2, "harmfulRank");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andCityRankIsNull() {
            addCriterion("city_rank is null");
            return (Criteria) this;
        }

        public Criteria andCityRankIsNotNull() {
            addCriterion("city_rank is not null");
            return (Criteria) this;
        }

        public Criteria andCityRankEqualTo(Integer value) {
            addCriterion("city_rank =", value, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankNotEqualTo(Integer value) {
            addCriterion("city_rank <>", value, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankGreaterThan(Integer value) {
            addCriterion("city_rank >", value, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_rank >=", value, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankLessThan(Integer value) {
            addCriterion("city_rank <", value, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankLessThanOrEqualTo(Integer value) {
            addCriterion("city_rank <=", value, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankIn(List<Integer> values) {
            addCriterion("city_rank in", values, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankNotIn(List<Integer> values) {
            addCriterion("city_rank not in", values, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankBetween(Integer value1, Integer value2) {
            addCriterion("city_rank between", value1, value2, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCityRankNotBetween(Integer value1, Integer value2) {
            addCriterion("city_rank not between", value1, value2, "cityRank");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_rank
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 06 20:16:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_rank
     *
     * @mbg.generated Mon Apr 06 20:16:29 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}